# Generated by Django 4.0.2 on 2022-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('git_id', models.IntegerField()),
                ('name', models.TextField(default=None, max_length=100)),
                ('label', models.TextField(default=None, max_length=1000)),
                ('avatar_url', models.TextField(default=None, max_length=500)),
                ('avatar', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
