# Generated by Django 4.0.2 on 2022-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0004_remove_platformuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='bio',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='blog',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='company',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='email',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='favourite_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='html_url',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='location',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='login',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='platform_type',
            field=models.TextField(default='GitHub', max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='public_gists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='public_repos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='avatar_url',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='git_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='label',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='name',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
