# Generated by Django 4.0.2 on 2022-02-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0005_platformuser_bio_platformuser_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='platform_type',
        ),
    ]
