# Generated by Django 4.0.2 on 2022-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0006_remove_platformuser_bio_remove_platformuser_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='favourite_star',
        ),
    ]
