# Generated by Django 4.0.2 on 2022-02-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0007_remove_platformuser_favourite_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='html_url',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='label',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='login',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='public_gists',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='public_repos',
        ),
    ]
