# Generated by Django 4.0.2 on 2022-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0008_remove_platformuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='avatar_url',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='email',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='favourite_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='html_url',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='label',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='login',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='name',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='public_gists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='public_repos',
            field=models.IntegerField(default=0),
        ),
    ]
