# Generated by Django 4.0.2 on 2022-02-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0009_platformuser_avatar_url_platformuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformUser',
        ),
    ]
