# Generated by Django 4.0.2 on 2022-02-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformUser',
        ),
    ]
