# Generated by Django 4.0.2 on 2022-02-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platformUsers', '0012_delete_platformuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_id', models.IntegerField(default=0)),
                ('name', models.TextField(default=None, max_length=200)),
                ('label', models.TextField(default=None, max_length=200)),
                ('avatar_url', models.TextField(default=None, max_length=200)),
                ('favourite', models.BooleanField(default=False)),
                ('html_url', models.TextField(default=None, max_length=200)),
                ('email', models.TextField(default=None, max_length=200)),
                ('login', models.TextField(default=None, max_length=200)),
                ('public_repos', models.IntegerField(default=0)),
                ('public_gists', models.IntegerField(default=0)),
                ('favourite_star', models.IntegerField(default=0)),
            ],
        ),
    ]
