# Generated by Django 4.0.2 on 2022-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='bio',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='blog',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='company',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='location',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='platform_type',
            field=models.TextField(default='GitHub', max_length=200),
        ),
    ]
