# Generated by Django 4.0.2 on 2022-02-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0015_alter_platformuser_bio_alter_platformuser_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='email',
            field=models.TextField(default='null@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='html_url',
            field=models.TextField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
