# Generated by Django 4.0.2 on 2022-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0016_alter_platformuser_email_alter_platformuser_html_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='avatar_url',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='bio',
            field=models.TextField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='blog',
            field=models.TextField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='company',
            field=models.TextField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='email',
            field=models.TextField(blank=True, default='null@gmail.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='label',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='location',
            field=models.TextField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='login',
            field=models.TextField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
