# Generated by Django 4.0.2 on 2022-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0017_alter_platformuser_avatar_url_alter_platformuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
